port: "7083"

control_host: "http://127.0.0.1:7081"

test_routing:
  - port: 8081
    path: "139.180.159.203,141.164.55.197,141.164.43.8:8081"

listeners:
  - proto: "tcp"
    port: 8081
    batch_num: 5
#  - proto: "tcp"
#    port: 8002
#  - proto: "udp"
#    port: 8002
#  - proto: "tcp"
#    port: 8003
#  - proto: "udp"
#    port: 8003
#  - proto: "tcp"
#    port: 8004
#  - proto: "tcp"
#    port: 8005
#  - proto: "udp"
#    port: 443   # HTTP3/QUIC
#  - proto: "tcp"
#    port: 443   # HTTPS

rate_limit:
  qps: 1000
  burst: 2000
  clean_interval: 5

aggregator:
  buffer_size: 5120
  batch_timeout_ms: 10

node:
  provider: "Vultr"
  continent: "Asia"
  country: "Korea"
  city: "Seoul"
  ip:
    private: "0.0.0.0"
    public: "141.164.55.197"