port: "7081"

ip_lib: "http://127.0.0.1:7082"

server_list:
  - "45.32.92.150"
server_ip: "45.32.92.150"
data_dir: "/root/etcd"
#name: "etcd-1"

# Node configuration - shared across modules
# See: ../config/node.yaml